@startuml

''save data
loop infinite
    loop 5 times
        ClockPendulumAnalyzer -> DataAssembler : getNewDataSample()
        DataAssembler -> Analyzer : getAbsoluteTimeNs()
        DataAssembler <-- Analyzer : int absoluteTime
        ClockPendulumAnalyzer <-- DataAssembler : DataTupel
        ClockPendulumAnalyzer -> ClockPendulumAnalyzer : wait(1s)
    end

    ClockPendulumAnalyzer -> DataTransfer : saveDataList()
    ClockPendulumAnalyzer <-- DataTransfer : bool isSaved
    alt isSaved == true
        ClockPendulumAnalyzer -> ClockPendulumAnalyzer : clearList
    end
end

@enduml
